# Generated by Django 4.1 on 2022-10-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friendship", "0004_auto_20200408_1844"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follow",
        ),
        migrations.AddField(
            model_name='friend',
            name='is_ping',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='is_mute',
            field=models.BooleanField(default=False),
        ),
    ]
