# Generated by Django 4.1 on 2022-10-05 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("friendship", "0004_auto_20200408_1844"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
